---

java_version: 11
java_packet: "java-{{java_version}}-openjdk-headless"

zookeeper_version: 3.5.8
zookeeper_package: "apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
zookeeper_id: 1
#zookeeper_url: "http://downloads.apache.org/zookeeper/zookeeper-{{zookeeper_version}}/{{ zookeeper_package }}"

app_dir: /app
distributes_dir: "{{app_dir}}/distrib"
zookeepr_data: "{{ app_dir }}/data/zookeeper"
zookeeper_log: "{{ app_dir }}/log/zookeeper"
zookeeper_dir: "{{app_dir}}/zookeeper"
app_dirs:
  - '{{ app_dir }}'
  - '{{ distributes_dir }}'
  - '{{ zookeepr_data }}'
  - '{{ zookeeper_log }}'
  - '{{ zookeeper_dir }}'


app_user_group: kafka

# Zookeeper variables
tick_time: 2000
client_port: 2181
init_limit: 5
sync_limit: 2
zookeeper_max_client_connections: 60
zookeeper_autopurge_purgeInterval: 0
zookeeper_autopurge_snapRetainCount: 10
zookeeper_cluster_followers_port: 2888
zookeeper_cluster_election_port: 3888
zookeeper_cluster_ports: "{{ zookeeper_cluster_followers_port }}:{{ zookeeper_cluster_election_port }}"
zk_ssl_enable: False
zk_quorum_ssl_enable: False
