---

- name: Creating directories if it does not exists.
  file:
    path: "{{ item }}"
    owner: "{{ app_user_group }}"
    group: "{{ app_user_group }}"
    state: directory
    mode: 0755
  loop: "{{ app_dirs_kafka|flatten(levels=1) }}"

- name: Download dist
  get_url:
    url: "{{ download_url }}/kafka/{{ kafka_package }}"
    dest: "{{ distributes_dir }}"
    mode: '0755'
    checksum: "{{ kafka_package_checksum }}"

- name: Unarchive binaries
  unarchive:
    src: "{{ distributes_dir }}/{{ kafka_package }}"
    dest: "{{ kafka_dir }}"
    group: '{{ app_user_group }}'
    owner: '{{ app_user_group }}'
    remote_src: yes
    mode: 0755
    extra_opts: [--strip-components=1]

- name: Template configuration file to server.properties
  template:
    src: server.properties.j2
    dest: '{{ kafka_dir }}/config/server.properties'
    group: '{{ app_user_group }}'
    owner: '{{ app_user_group }}'

- name: Template client.properties                                                                                                                                
  template:
    src: client.properties.j2
    dest: "{{kafka_dir}}/config/client.properties"

- name: Template log4j.properties                                                                                                                                 
  template:
    src: kafka-log4j.properties.j2
    dest: '{{ kafka_dir }}/config/log4j.properties'

- name: Create kafka systemd service                                                                                                                              
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
  notify:
    - restart kafka

- name: Create kafka systemd service conf                                                                                                                         
  template:
    src: kafka.service.conf.j2
    dest: /etc/systemd/system/kafka.service.conf

- name: Install and start the kafka service                                                                                                                       
  systemd:
    name: kafka
    state: started
    enabled: yes
    daemon_reload: yes
