---

- name: Setting dir for pid files
  copy:
    src: "zookeeper.conf"
    dest: "/etc/tmpfiles.d"
    group: 'root'
    owner: 'root'
    mode: 0644

- name: Download dist
  get_url:
    url: https://downloads.apache.org/zookeeper/zookeeper-3.5.8/apache-zookeeper-3.5.8-bin.tar.gz
    dest: "{{ distributes_dir }}"
    mode: '0755'
  #delegate_to: localhost
  #run_once: true
  #ignore_errors: true

- name: Unpacking Zookeeper
  unarchive:
    src: "{{ distributes_dir }}/{{ zookeeper_package }}"
    dest: "{{ zookeeper_dir }}"
    remote_src: yes
    group: '{{ app_user_group }}'
    owner: '{{ app_user_group }}'
    mode: 0755
    extra_opts: [--strip-components=1]

- name: Updating log4j.properties
  template:
    src: "log4j.properties.j2"
    dest: "{{ zookeeper_dir }}/conf/log4j.properties"
    group: "{{ app_user_group }}"
    owner: "{{ app_user_group }}"

- name: Creating myid file.
  template:
    src: "myid.j2"
    dest: "{{ zookeepr_data }}/myid"
    group: "{{ app_user_group }}"
    owner: "{{ app_user_group }}"

- name: Create zookeeper config
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_dir }}/conf/zoo.cfg"
    group: "{{ app_user_group }}"
    owner: "{{ app_user_group }}"

- name: Create zookeeper systemd service conf                                                                                                                     
  template:
    src: zookeeper.service.conf.j2
    dest: /etc/systemd/system/zookeeper.service.conf

- name: Create systemd script.                                                                                                                                    
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart zookeeper

- name: Enable zookeeper service                                                                                                                                  
  systemd:
    name: zookeeper
    state: started
    enabled: yes
