---

- name: Installing Java if it absent.
  package:
    name: "{{ java_packet }}"
    state: present

- name: Getting JAVA_HOME
  shell: "grep 'java-{{java_version}}-openjdk.*/bin/java' /var/lib/alternatives/java | sed 's/\\/bin\\/java//'"
  register: java_home

- name: Setting JAVA_HOME environment variables.
  template:
    src: java.sh.j2
    dest: /etc/profile.d/java.sh
    mode: 0644