---

# Prerequisites
- include_tasks: prerequisites.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

# Install Zookeeper
- include_tasks: install_zookeeper.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'  